#!/bin/bash

# Host kernel (Fedora 43+) uses nftables; Docker-in-Docker needs the nft backend
sudo update-alternatives --set iptables /usr/sbin/iptables-nft
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-nft

/usr/local/bin/mise trust && /usr/local/bin/mise install
