#!/bin/bash

# Run in DevPod  or devcontainer 
if [ "$DEVPOD" = "true" ] || [ -n "$DEVCONTAINER" ]; then

# These run every time the container is created
git config --global push.autoSetupRemote true
git config --global --add safe.directory /workspaces/study-app

# Install tools globally via pipx 
pipx install commitizen --force
pipx install pre-commit --force

# Setup git hooks
pre-commit install
pre-commit install --hook-type commit-msg

fi
