#!/bin/bash

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then

# These run every time the container is created
git config --global push.autoSetupRemote true
git config --global --add safe.directory /workspaces/study-app

# Install tools globally via pipx (this is safe to run multiple times)
pipx install commitizen --force
pipx install pre-commit --force

# Setup git hooks
pre-commit install
pre-commit install --hook-type commit-msg

fi
